#!/usr/bin/python3 -cimport os, sys; os.execv(os.path.dirname(sys.argv[1]) + "/common/pywrap", sys.argv)

import testlib


@testlib.nondestructive
class TestApplication(testlib.MachineCase):
    def testBasic(self):
        b = self.browser

        self.login_and_go("/nixos-manager")
        b.wait_text("h1", "NixOS Manager")
        b.wait_in_text("body", "GitOps lifecycle")


if __name__ == '__main__':
    testlib.test_main()
