name: Check

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: "22"

      - name: Generate npm lockfile
        run: npm install --package-lock-only --ignore-scripts

      - name: Upload npm lockfile
        uses: actions/upload-artifact@v4
        with:
          name: npm-lockfile
          path: package-lock.json

      - name: Build
        run: make

      - name: Lint TypeScript
        run: npm run eslint

      - name: Lint styles
        run: npm run stylelint
